name: publish jar
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle' # Thay đổi từ 'maven' sang 'gradle'
      - name: Build jar
        run: ./gradlew shadowJar # Tương đương với mvn -B clean package -DskipTests
      # - name: publish gradle jar
      #   run: ./gradlew publish -x test # Tương đương với mvn -B deploy -DskipTests
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename artifact
        run: mv build/libs/ysoserial-${{ github.ref_name }}-all.jar build/libs/ysoserial-all.jar

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          files: build/libs/ysoserial-all.jar
